### ISSUE TITLE
There is some potential issue

### ISSUE THREAD

**Issue by kazimovzaman2** [HolbertonPortfolio/CakeyBackEndTemp#1]
```
docker build . --file Dockerfile --tag my-image-name:latest
docker push my-image-name:latest
```

I think you need to login docker hub first, then build docker image and push it.

something like this
```
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
```
